/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRecontagemRouteImport } from './routes/_authenticated/recontagem'
import { Route as AuthenticatedQuebrasFefoRouteImport } from './routes/_authenticated/quebras-fefo'
import { Route as AuthenticatedOrigensRouteImport } from './routes/_authenticated/origens'
import { Route as AuthenticatedMotivosBaixaRouteImport } from './routes/_authenticated/motivos-baixa'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedImportarFamiliasRouteImport } from './routes/_authenticated/importar-familias'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedGruposRouteImport } from './routes/_authenticated/grupos'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated/emails'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContarRouteImport } from './routes/_authenticated/contar'
import { Route as AuthenticatedAbcRouteImport } from './routes/_authenticated/abc'
import { Route as AuthenticatedMissoesIndexRouteImport } from './routes/_authenticated/missoes.index'
import { Route as AuthenticatedConfigIndexRouteImport } from './routes/_authenticated/config.index'
import { Route as AuthenticatedBaixasIndexRouteImport } from './routes/_authenticated/baixas.index'
import { Route as ApiPublicImportFichaTecnicaBomRouteImport } from './routes/api/public/import-ficha-tecnica-bom'
import { Route as ApiPublicImportEstoqueSistemicoRouteImport } from './routes/api/public/import-estoque-sistemico'
import { Route as ApiPublicImportConsumoOpRouteImport } from './routes/api/public/import-consumo-op'
import { Route as ApiPublicImportConsumoCmdRouteImport } from './routes/api/public/import-consumo-cmd'
import { Route as ApiPublicAtlasExportarBaixasRouteImport } from './routes/api/public/atlas-exportar-baixas'
import { Route as AuthenticatedSuprimentosEstoqueRouteImport } from './routes/_authenticated/suprimentos.estoque'
import { Route as AuthenticatedSuprimentosDashboardRouteImport } from './routes/_authenticated/suprimentos.dashboard'
import { Route as AuthenticatedShelfLifeRiscoRouteImport } from './routes/_authenticated/shelf-life.risco'
import { Route as AuthenticatedShelfLifePrecosRouteImport } from './routes/_authenticated/shelf-life.precos'
import { Route as AuthenticatedShelfLifeFarolRouteImport } from './routes/_authenticated/shelf-life.farol'
import { Route as AuthenticatedShelfLifeDashboardRouteImport } from './routes/_authenticated/shelf-life.dashboard'
import { Route as AuthenticatedShelfLifeAcoesRouteImport } from './routes/_authenticated/shelf-life.acoes'
import { Route as AuthenticatedProducaoTestesIndustriaisRouteImport } from './routes/_authenticated/producao.testes-industriais'
import { Route as AuthenticatedProducaoSolicitacaoMateriaisRouteImport } from './routes/_authenticated/producao.solicitacao-materiais'
import { Route as AuthenticatedProducaoPcpRouteImport } from './routes/_authenticated/producao.pcp'
import { Route as AuthenticatedProducaoDispersaoRouteImport } from './routes/_authenticated/producao.dispersao'
import { Route as AuthenticatedProducaoAuditoriaFtRouteImport } from './routes/_authenticated/producao.auditoria-ft'
import { Route as AuthenticatedMissoesIdRouteImport } from './routes/_authenticated/missoes.$id'
import { Route as AuthenticatedGestaoPlanejamentoRouteImport } from './routes/_authenticated/gestao.planejamento'
import { Route as AuthenticatedGestaoModelosChecklistRouteImport } from './routes/_authenticated/gestao.modelos-checklist'
import { Route as AuthenticatedGestaoMinhasTarefasRouteImport } from './routes/_authenticated/gestao.minhas-tarefas'
import { Route as AuthenticatedConfigSazonalidadeRouteImport } from './routes/_authenticated/config.sazonalidade'
import { Route as AuthenticatedConfigResendRouteImport } from './routes/_authenticated/config.resend'
import { Route as AuthenticatedConfigPerfisRouteImport } from './routes/_authenticated/config.perfis'
import { Route as AuthenticatedConfigInventarioRouteImport } from './routes/_authenticated/config.inventario'
import { Route as AuthenticatedConfigDispersaoRouteImport } from './routes/_authenticated/config.dispersao'
import { Route as AuthenticatedConfigAparenciaRouteImport } from './routes/_authenticated/config.aparencia'
import { Route as AuthenticatedBaixasDashboardRouteImport } from './routes/_authenticated/baixas.dashboard'
import { Route as AuthenticatedAbastecimentoPlanejamentoRouteImport } from './routes/_authenticated/abastecimento.planejamento'
import { Route as AuthenticatedAbastecimentoParametrosRouteImport } from './routes/_authenticated/abastecimento.parametros'
import { Route as AuthenticatedAbastecimentoDemandasRouteImport } from './routes/_authenticated/abastecimento.demandas'
import { Route as AuthenticatedAbastecimentoConsumoRouteImport } from './routes/_authenticated/abastecimento.consumo'
import { Route as AuthenticatedSuprimentosRequisicoesIndexRouteImport } from './routes/_authenticated/suprimentos.requisicoes.index'
import { Route as ApiPublicHooksResumoTarefasRouteImport } from './routes/api/public/hooks/resumo-tarefas'
import { Route as AuthenticatedSuprimentosRequisicoesIdRouteImport } from './routes/_authenticated/suprimentos.requisicoes.$id'
import { Route as AuthenticatedProducaoMaterialMaterialRouteImport } from './routes/_authenticated/producao.material.$material'
import { Route as AuthenticatedSuprimentosRequisicoesIdFichaRouteImport } from './routes/_authenticated/suprimentos.requisicoes.$id.ficha'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecontagemRoute = AuthenticatedRecontagemRouteImport.update({
  id: '/recontagem',
  path: '/recontagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuebrasFefoRoute =
  AuthenticatedQuebrasFefoRouteImport.update({
    id: '/quebras-fefo',
    path: '/quebras-fefo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrigensRoute = AuthenticatedOrigensRouteImport.update({
  id: '/origens',
  path: '/origens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotivosBaixaRoute =
  AuthenticatedMotivosBaixaRouteImport.update({
    id: '/motivos-baixa',
    path: '/motivos-baixa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarFamiliasRoute =
  AuthenticatedImportarFamiliasRouteImport.update({
    id: '/importar-familias',
    path: '/importar-familias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGruposRoute = AuthenticatedGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContarRoute = AuthenticatedContarRouteImport.update({
  id: '/contar',
  path: '/contar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAbcRoute = AuthenticatedAbcRouteImport.update({
  id: '/abc',
  path: '/abc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissoesIndexRoute =
  AuthenticatedMissoesIndexRouteImport.update({
    id: '/missoes/',
    path: '/missoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigIndexRoute =
  AuthenticatedConfigIndexRouteImport.update({
    id: '/config/',
    path: '/config/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBaixasIndexRoute =
  AuthenticatedBaixasIndexRouteImport.update({
    id: '/baixas/',
    path: '/baixas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicImportFichaTecnicaBomRoute =
  ApiPublicImportFichaTecnicaBomRouteImport.update({
    id: '/api/public/import-ficha-tecnica-bom',
    path: '/api/public/import-ficha-tecnica-bom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicImportEstoqueSistemicoRoute =
  ApiPublicImportEstoqueSistemicoRouteImport.update({
    id: '/api/public/import-estoque-sistemico',
    path: '/api/public/import-estoque-sistemico',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicImportConsumoOpRoute =
  ApiPublicImportConsumoOpRouteImport.update({
    id: '/api/public/import-consumo-op',
    path: '/api/public/import-consumo-op',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicImportConsumoCmdRoute =
  ApiPublicImportConsumoCmdRouteImport.update({
    id: '/api/public/import-consumo-cmd',
    path: '/api/public/import-consumo-cmd',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAtlasExportarBaixasRoute =
  ApiPublicAtlasExportarBaixasRouteImport.update({
    id: '/api/public/atlas-exportar-baixas',
    path: '/api/public/atlas-exportar-baixas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSuprimentosEstoqueRoute =
  AuthenticatedSuprimentosEstoqueRouteImport.update({
    id: '/suprimentos/estoque',
    path: '/suprimentos/estoque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuprimentosDashboardRoute =
  AuthenticatedSuprimentosDashboardRouteImport.update({
    id: '/suprimentos/dashboard',
    path: '/suprimentos/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShelfLifeRiscoRoute =
  AuthenticatedShelfLifeRiscoRouteImport.update({
    id: '/shelf-life/risco',
    path: '/shelf-life/risco',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShelfLifePrecosRoute =
  AuthenticatedShelfLifePrecosRouteImport.update({
    id: '/shelf-life/precos',
    path: '/shelf-life/precos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShelfLifeFarolRoute =
  AuthenticatedShelfLifeFarolRouteImport.update({
    id: '/shelf-life/farol',
    path: '/shelf-life/farol',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShelfLifeDashboardRoute =
  AuthenticatedShelfLifeDashboardRouteImport.update({
    id: '/shelf-life/dashboard',
    path: '/shelf-life/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShelfLifeAcoesRoute =
  AuthenticatedShelfLifeAcoesRouteImport.update({
    id: '/shelf-life/acoes',
    path: '/shelf-life/acoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProducaoTestesIndustriaisRoute =
  AuthenticatedProducaoTestesIndustriaisRouteImport.update({
    id: '/producao/testes-industriais',
    path: '/producao/testes-industriais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProducaoSolicitacaoMateriaisRoute =
  AuthenticatedProducaoSolicitacaoMateriaisRouteImport.update({
    id: '/producao/solicitacao-materiais',
    path: '/producao/solicitacao-materiais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProducaoPcpRoute =
  AuthenticatedProducaoPcpRouteImport.update({
    id: '/producao/pcp',
    path: '/producao/pcp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProducaoDispersaoRoute =
  AuthenticatedProducaoDispersaoRouteImport.update({
    id: '/producao/dispersao',
    path: '/producao/dispersao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProducaoAuditoriaFtRoute =
  AuthenticatedProducaoAuditoriaFtRouteImport.update({
    id: '/producao/auditoria-ft',
    path: '/producao/auditoria-ft',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissoesIdRoute = AuthenticatedMissoesIdRouteImport.update({
  id: '/missoes/$id',
  path: '/missoes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestaoPlanejamentoRoute =
  AuthenticatedGestaoPlanejamentoRouteImport.update({
    id: '/gestao/planejamento',
    path: '/gestao/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestaoModelosChecklistRoute =
  AuthenticatedGestaoModelosChecklistRouteImport.update({
    id: '/gestao/modelos-checklist',
    path: '/gestao/modelos-checklist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestaoMinhasTarefasRoute =
  AuthenticatedGestaoMinhasTarefasRouteImport.update({
    id: '/gestao/minhas-tarefas',
    path: '/gestao/minhas-tarefas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigSazonalidadeRoute =
  AuthenticatedConfigSazonalidadeRouteImport.update({
    id: '/config/sazonalidade',
    path: '/config/sazonalidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigResendRoute =
  AuthenticatedConfigResendRouteImport.update({
    id: '/config/resend',
    path: '/config/resend',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigPerfisRoute =
  AuthenticatedConfigPerfisRouteImport.update({
    id: '/config/perfis',
    path: '/config/perfis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigInventarioRoute =
  AuthenticatedConfigInventarioRouteImport.update({
    id: '/config/inventario',
    path: '/config/inventario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigDispersaoRoute =
  AuthenticatedConfigDispersaoRouteImport.update({
    id: '/config/dispersao',
    path: '/config/dispersao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigAparenciaRoute =
  AuthenticatedConfigAparenciaRouteImport.update({
    id: '/config/aparencia',
    path: '/config/aparencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBaixasDashboardRoute =
  AuthenticatedBaixasDashboardRouteImport.update({
    id: '/baixas/dashboard',
    path: '/baixas/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAbastecimentoPlanejamentoRoute =
  AuthenticatedAbastecimentoPlanejamentoRouteImport.update({
    id: '/abastecimento/planejamento',
    path: '/abastecimento/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAbastecimentoParametrosRoute =
  AuthenticatedAbastecimentoParametrosRouteImport.update({
    id: '/abastecimento/parametros',
    path: '/abastecimento/parametros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAbastecimentoDemandasRoute =
  AuthenticatedAbastecimentoDemandasRouteImport.update({
    id: '/abastecimento/demandas',
    path: '/abastecimento/demandas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAbastecimentoConsumoRoute =
  AuthenticatedAbastecimentoConsumoRouteImport.update({
    id: '/abastecimento/consumo',
    path: '/abastecimento/consumo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuprimentosRequisicoesIndexRoute =
  AuthenticatedSuprimentosRequisicoesIndexRouteImport.update({
    id: '/suprimentos/requisicoes/',
    path: '/suprimentos/requisicoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksResumoTarefasRoute =
  ApiPublicHooksResumoTarefasRouteImport.update({
    id: '/api/public/hooks/resumo-tarefas',
    path: '/api/public/hooks/resumo-tarefas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSuprimentosRequisicoesIdRoute =
  AuthenticatedSuprimentosRequisicoesIdRouteImport.update({
    id: '/suprimentos/requisicoes/$id',
    path: '/suprimentos/requisicoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProducaoMaterialMaterialRoute =
  AuthenticatedProducaoMaterialMaterialRouteImport.update({
    id: '/producao/material/$material',
    path: '/producao/material/$material',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuprimentosRequisicoesIdFichaRoute =
  AuthenticatedSuprimentosRequisicoesIdFichaRouteImport.update({
    id: '/ficha',
    path: '/ficha',
    getParentRoute: () => AuthenticatedSuprimentosRequisicoesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/abc': typeof AuthenticatedAbcRoute
  '/contar': typeof AuthenticatedContarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/importar-familias': typeof AuthenticatedImportarFamiliasRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/motivos-baixa': typeof AuthenticatedMotivosBaixaRoute
  '/origens': typeof AuthenticatedOrigensRoute
  '/quebras-fefo': typeof AuthenticatedQuebrasFefoRoute
  '/recontagem': typeof AuthenticatedRecontagemRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/abastecimento/consumo': typeof AuthenticatedAbastecimentoConsumoRoute
  '/abastecimento/demandas': typeof AuthenticatedAbastecimentoDemandasRoute
  '/abastecimento/parametros': typeof AuthenticatedAbastecimentoParametrosRoute
  '/abastecimento/planejamento': typeof AuthenticatedAbastecimentoPlanejamentoRoute
  '/baixas/dashboard': typeof AuthenticatedBaixasDashboardRoute
  '/config/aparencia': typeof AuthenticatedConfigAparenciaRoute
  '/config/dispersao': typeof AuthenticatedConfigDispersaoRoute
  '/config/inventario': typeof AuthenticatedConfigInventarioRoute
  '/config/perfis': typeof AuthenticatedConfigPerfisRoute
  '/config/resend': typeof AuthenticatedConfigResendRoute
  '/config/sazonalidade': typeof AuthenticatedConfigSazonalidadeRoute
  '/gestao/minhas-tarefas': typeof AuthenticatedGestaoMinhasTarefasRoute
  '/gestao/modelos-checklist': typeof AuthenticatedGestaoModelosChecklistRoute
  '/gestao/planejamento': typeof AuthenticatedGestaoPlanejamentoRoute
  '/missoes/$id': typeof AuthenticatedMissoesIdRoute
  '/producao/auditoria-ft': typeof AuthenticatedProducaoAuditoriaFtRoute
  '/producao/dispersao': typeof AuthenticatedProducaoDispersaoRoute
  '/producao/pcp': typeof AuthenticatedProducaoPcpRoute
  '/producao/solicitacao-materiais': typeof AuthenticatedProducaoSolicitacaoMateriaisRoute
  '/producao/testes-industriais': typeof AuthenticatedProducaoTestesIndustriaisRoute
  '/shelf-life/acoes': typeof AuthenticatedShelfLifeAcoesRoute
  '/shelf-life/dashboard': typeof AuthenticatedShelfLifeDashboardRoute
  '/shelf-life/farol': typeof AuthenticatedShelfLifeFarolRoute
  '/shelf-life/precos': typeof AuthenticatedShelfLifePrecosRoute
  '/shelf-life/risco': typeof AuthenticatedShelfLifeRiscoRoute
  '/suprimentos/dashboard': typeof AuthenticatedSuprimentosDashboardRoute
  '/suprimentos/estoque': typeof AuthenticatedSuprimentosEstoqueRoute
  '/api/public/atlas-exportar-baixas': typeof ApiPublicAtlasExportarBaixasRoute
  '/api/public/import-consumo-cmd': typeof ApiPublicImportConsumoCmdRoute
  '/api/public/import-consumo-op': typeof ApiPublicImportConsumoOpRoute
  '/api/public/import-estoque-sistemico': typeof ApiPublicImportEstoqueSistemicoRoute
  '/api/public/import-ficha-tecnica-bom': typeof ApiPublicImportFichaTecnicaBomRoute
  '/baixas/': typeof AuthenticatedBaixasIndexRoute
  '/config/': typeof AuthenticatedConfigIndexRoute
  '/missoes/': typeof AuthenticatedMissoesIndexRoute
  '/producao/material/$material': typeof AuthenticatedProducaoMaterialMaterialRoute
  '/suprimentos/requisicoes/$id': typeof AuthenticatedSuprimentosRequisicoesIdRouteWithChildren
  '/api/public/hooks/resumo-tarefas': typeof ApiPublicHooksResumoTarefasRoute
  '/suprimentos/requisicoes/': typeof AuthenticatedSuprimentosRequisicoesIndexRoute
  '/suprimentos/requisicoes/$id/ficha': typeof AuthenticatedSuprimentosRequisicoesIdFichaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/abc': typeof AuthenticatedAbcRoute
  '/contar': typeof AuthenticatedContarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/importar-familias': typeof AuthenticatedImportarFamiliasRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/motivos-baixa': typeof AuthenticatedMotivosBaixaRoute
  '/origens': typeof AuthenticatedOrigensRoute
  '/quebras-fefo': typeof AuthenticatedQuebrasFefoRoute
  '/recontagem': typeof AuthenticatedRecontagemRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/abastecimento/consumo': typeof AuthenticatedAbastecimentoConsumoRoute
  '/abastecimento/demandas': typeof AuthenticatedAbastecimentoDemandasRoute
  '/abastecimento/parametros': typeof AuthenticatedAbastecimentoParametrosRoute
  '/abastecimento/planejamento': typeof AuthenticatedAbastecimentoPlanejamentoRoute
  '/baixas/dashboard': typeof AuthenticatedBaixasDashboardRoute
  '/config/aparencia': typeof AuthenticatedConfigAparenciaRoute
  '/config/dispersao': typeof AuthenticatedConfigDispersaoRoute
  '/config/inventario': typeof AuthenticatedConfigInventarioRoute
  '/config/perfis': typeof AuthenticatedConfigPerfisRoute
  '/config/resend': typeof AuthenticatedConfigResendRoute
  '/config/sazonalidade': typeof AuthenticatedConfigSazonalidadeRoute
  '/gestao/minhas-tarefas': typeof AuthenticatedGestaoMinhasTarefasRoute
  '/gestao/modelos-checklist': typeof AuthenticatedGestaoModelosChecklistRoute
  '/gestao/planejamento': typeof AuthenticatedGestaoPlanejamentoRoute
  '/missoes/$id': typeof AuthenticatedMissoesIdRoute
  '/producao/auditoria-ft': typeof AuthenticatedProducaoAuditoriaFtRoute
  '/producao/dispersao': typeof AuthenticatedProducaoDispersaoRoute
  '/producao/pcp': typeof AuthenticatedProducaoPcpRoute
  '/producao/solicitacao-materiais': typeof AuthenticatedProducaoSolicitacaoMateriaisRoute
  '/producao/testes-industriais': typeof AuthenticatedProducaoTestesIndustriaisRoute
  '/shelf-life/acoes': typeof AuthenticatedShelfLifeAcoesRoute
  '/shelf-life/dashboard': typeof AuthenticatedShelfLifeDashboardRoute
  '/shelf-life/farol': typeof AuthenticatedShelfLifeFarolRoute
  '/shelf-life/precos': typeof AuthenticatedShelfLifePrecosRoute
  '/shelf-life/risco': typeof AuthenticatedShelfLifeRiscoRoute
  '/suprimentos/dashboard': typeof AuthenticatedSuprimentosDashboardRoute
  '/suprimentos/estoque': typeof AuthenticatedSuprimentosEstoqueRoute
  '/api/public/atlas-exportar-baixas': typeof ApiPublicAtlasExportarBaixasRoute
  '/api/public/import-consumo-cmd': typeof ApiPublicImportConsumoCmdRoute
  '/api/public/import-consumo-op': typeof ApiPublicImportConsumoOpRoute
  '/api/public/import-estoque-sistemico': typeof ApiPublicImportEstoqueSistemicoRoute
  '/api/public/import-ficha-tecnica-bom': typeof ApiPublicImportFichaTecnicaBomRoute
  '/baixas': typeof AuthenticatedBaixasIndexRoute
  '/config': typeof AuthenticatedConfigIndexRoute
  '/missoes': typeof AuthenticatedMissoesIndexRoute
  '/producao/material/$material': typeof AuthenticatedProducaoMaterialMaterialRoute
  '/suprimentos/requisicoes/$id': typeof AuthenticatedSuprimentosRequisicoesIdRouteWithChildren
  '/api/public/hooks/resumo-tarefas': typeof ApiPublicHooksResumoTarefasRoute
  '/suprimentos/requisicoes': typeof AuthenticatedSuprimentosRequisicoesIndexRoute
  '/suprimentos/requisicoes/$id/ficha': typeof AuthenticatedSuprimentosRequisicoesIdFichaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/abc': typeof AuthenticatedAbcRoute
  '/_authenticated/contar': typeof AuthenticatedContarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/grupos': typeof AuthenticatedGruposRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/importar-familias': typeof AuthenticatedImportarFamiliasRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/motivos-baixa': typeof AuthenticatedMotivosBaixaRoute
  '/_authenticated/origens': typeof AuthenticatedOrigensRoute
  '/_authenticated/quebras-fefo': typeof AuthenticatedQuebrasFefoRoute
  '/_authenticated/recontagem': typeof AuthenticatedRecontagemRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/abastecimento/consumo': typeof AuthenticatedAbastecimentoConsumoRoute
  '/_authenticated/abastecimento/demandas': typeof AuthenticatedAbastecimentoDemandasRoute
  '/_authenticated/abastecimento/parametros': typeof AuthenticatedAbastecimentoParametrosRoute
  '/_authenticated/abastecimento/planejamento': typeof AuthenticatedAbastecimentoPlanejamentoRoute
  '/_authenticated/baixas/dashboard': typeof AuthenticatedBaixasDashboardRoute
  '/_authenticated/config/aparencia': typeof AuthenticatedConfigAparenciaRoute
  '/_authenticated/config/dispersao': typeof AuthenticatedConfigDispersaoRoute
  '/_authenticated/config/inventario': typeof AuthenticatedConfigInventarioRoute
  '/_authenticated/config/perfis': typeof AuthenticatedConfigPerfisRoute
  '/_authenticated/config/resend': typeof AuthenticatedConfigResendRoute
  '/_authenticated/config/sazonalidade': typeof AuthenticatedConfigSazonalidadeRoute
  '/_authenticated/gestao/minhas-tarefas': typeof AuthenticatedGestaoMinhasTarefasRoute
  '/_authenticated/gestao/modelos-checklist': typeof AuthenticatedGestaoModelosChecklistRoute
  '/_authenticated/gestao/planejamento': typeof AuthenticatedGestaoPlanejamentoRoute
  '/_authenticated/missoes/$id': typeof AuthenticatedMissoesIdRoute
  '/_authenticated/producao/auditoria-ft': typeof AuthenticatedProducaoAuditoriaFtRoute
  '/_authenticated/producao/dispersao': typeof AuthenticatedProducaoDispersaoRoute
  '/_authenticated/producao/pcp': typeof AuthenticatedProducaoPcpRoute
  '/_authenticated/producao/solicitacao-materiais': typeof AuthenticatedProducaoSolicitacaoMateriaisRoute
  '/_authenticated/producao/testes-industriais': typeof AuthenticatedProducaoTestesIndustriaisRoute
  '/_authenticated/shelf-life/acoes': typeof AuthenticatedShelfLifeAcoesRoute
  '/_authenticated/shelf-life/dashboard': typeof AuthenticatedShelfLifeDashboardRoute
  '/_authenticated/shelf-life/farol': typeof AuthenticatedShelfLifeFarolRoute
  '/_authenticated/shelf-life/precos': typeof AuthenticatedShelfLifePrecosRoute
  '/_authenticated/shelf-life/risco': typeof AuthenticatedShelfLifeRiscoRoute
  '/_authenticated/suprimentos/dashboard': typeof AuthenticatedSuprimentosDashboardRoute
  '/_authenticated/suprimentos/estoque': typeof AuthenticatedSuprimentosEstoqueRoute
  '/api/public/atlas-exportar-baixas': typeof ApiPublicAtlasExportarBaixasRoute
  '/api/public/import-consumo-cmd': typeof ApiPublicImportConsumoCmdRoute
  '/api/public/import-consumo-op': typeof ApiPublicImportConsumoOpRoute
  '/api/public/import-estoque-sistemico': typeof ApiPublicImportEstoqueSistemicoRoute
  '/api/public/import-ficha-tecnica-bom': typeof ApiPublicImportFichaTecnicaBomRoute
  '/_authenticated/baixas/': typeof AuthenticatedBaixasIndexRoute
  '/_authenticated/config/': typeof AuthenticatedConfigIndexRoute
  '/_authenticated/missoes/': typeof AuthenticatedMissoesIndexRoute
  '/_authenticated/producao/material/$material': typeof AuthenticatedProducaoMaterialMaterialRoute
  '/_authenticated/suprimentos/requisicoes/$id': typeof AuthenticatedSuprimentosRequisicoesIdRouteWithChildren
  '/api/public/hooks/resumo-tarefas': typeof ApiPublicHooksResumoTarefasRoute
  '/_authenticated/suprimentos/requisicoes/': typeof AuthenticatedSuprimentosRequisicoesIndexRoute
  '/_authenticated/suprimentos/requisicoes/$id/ficha': typeof AuthenticatedSuprimentosRequisicoesIdFichaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/abc'
    | '/contar'
    | '/dashboard'
    | '/emails'
    | '/grupos'
    | '/importar'
    | '/importar-familias'
    | '/inventario'
    | '/logs'
    | '/motivos-baixa'
    | '/origens'
    | '/quebras-fefo'
    | '/recontagem'
    | '/relatorios'
    | '/scanner'
    | '/usuarios'
    | '/abastecimento/consumo'
    | '/abastecimento/demandas'
    | '/abastecimento/parametros'
    | '/abastecimento/planejamento'
    | '/baixas/dashboard'
    | '/config/aparencia'
    | '/config/dispersao'
    | '/config/inventario'
    | '/config/perfis'
    | '/config/resend'
    | '/config/sazonalidade'
    | '/gestao/minhas-tarefas'
    | '/gestao/modelos-checklist'
    | '/gestao/planejamento'
    | '/missoes/$id'
    | '/producao/auditoria-ft'
    | '/producao/dispersao'
    | '/producao/pcp'
    | '/producao/solicitacao-materiais'
    | '/producao/testes-industriais'
    | '/shelf-life/acoes'
    | '/shelf-life/dashboard'
    | '/shelf-life/farol'
    | '/shelf-life/precos'
    | '/shelf-life/risco'
    | '/suprimentos/dashboard'
    | '/suprimentos/estoque'
    | '/api/public/atlas-exportar-baixas'
    | '/api/public/import-consumo-cmd'
    | '/api/public/import-consumo-op'
    | '/api/public/import-estoque-sistemico'
    | '/api/public/import-ficha-tecnica-bom'
    | '/baixas/'
    | '/config/'
    | '/missoes/'
    | '/producao/material/$material'
    | '/suprimentos/requisicoes/$id'
    | '/api/public/hooks/resumo-tarefas'
    | '/suprimentos/requisicoes/'
    | '/suprimentos/requisicoes/$id/ficha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/abc'
    | '/contar'
    | '/dashboard'
    | '/emails'
    | '/grupos'
    | '/importar'
    | '/importar-familias'
    | '/inventario'
    | '/logs'
    | '/motivos-baixa'
    | '/origens'
    | '/quebras-fefo'
    | '/recontagem'
    | '/relatorios'
    | '/scanner'
    | '/usuarios'
    | '/abastecimento/consumo'
    | '/abastecimento/demandas'
    | '/abastecimento/parametros'
    | '/abastecimento/planejamento'
    | '/baixas/dashboard'
    | '/config/aparencia'
    | '/config/dispersao'
    | '/config/inventario'
    | '/config/perfis'
    | '/config/resend'
    | '/config/sazonalidade'
    | '/gestao/minhas-tarefas'
    | '/gestao/modelos-checklist'
    | '/gestao/planejamento'
    | '/missoes/$id'
    | '/producao/auditoria-ft'
    | '/producao/dispersao'
    | '/producao/pcp'
    | '/producao/solicitacao-materiais'
    | '/producao/testes-industriais'
    | '/shelf-life/acoes'
    | '/shelf-life/dashboard'
    | '/shelf-life/farol'
    | '/shelf-life/precos'
    | '/shelf-life/risco'
    | '/suprimentos/dashboard'
    | '/suprimentos/estoque'
    | '/api/public/atlas-exportar-baixas'
    | '/api/public/import-consumo-cmd'
    | '/api/public/import-consumo-op'
    | '/api/public/import-estoque-sistemico'
    | '/api/public/import-ficha-tecnica-bom'
    | '/baixas'
    | '/config'
    | '/missoes'
    | '/producao/material/$material'
    | '/suprimentos/requisicoes/$id'
    | '/api/public/hooks/resumo-tarefas'
    | '/suprimentos/requisicoes'
    | '/suprimentos/requisicoes/$id/ficha'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/abc'
    | '/_authenticated/contar'
    | '/_authenticated/dashboard'
    | '/_authenticated/emails'
    | '/_authenticated/grupos'
    | '/_authenticated/importar'
    | '/_authenticated/importar-familias'
    | '/_authenticated/inventario'
    | '/_authenticated/logs'
    | '/_authenticated/motivos-baixa'
    | '/_authenticated/origens'
    | '/_authenticated/quebras-fefo'
    | '/_authenticated/recontagem'
    | '/_authenticated/relatorios'
    | '/_authenticated/scanner'
    | '/_authenticated/usuarios'
    | '/_authenticated/abastecimento/consumo'
    | '/_authenticated/abastecimento/demandas'
    | '/_authenticated/abastecimento/parametros'
    | '/_authenticated/abastecimento/planejamento'
    | '/_authenticated/baixas/dashboard'
    | '/_authenticated/config/aparencia'
    | '/_authenticated/config/dispersao'
    | '/_authenticated/config/inventario'
    | '/_authenticated/config/perfis'
    | '/_authenticated/config/resend'
    | '/_authenticated/config/sazonalidade'
    | '/_authenticated/gestao/minhas-tarefas'
    | '/_authenticated/gestao/modelos-checklist'
    | '/_authenticated/gestao/planejamento'
    | '/_authenticated/missoes/$id'
    | '/_authenticated/producao/auditoria-ft'
    | '/_authenticated/producao/dispersao'
    | '/_authenticated/producao/pcp'
    | '/_authenticated/producao/solicitacao-materiais'
    | '/_authenticated/producao/testes-industriais'
    | '/_authenticated/shelf-life/acoes'
    | '/_authenticated/shelf-life/dashboard'
    | '/_authenticated/shelf-life/farol'
    | '/_authenticated/shelf-life/precos'
    | '/_authenticated/shelf-life/risco'
    | '/_authenticated/suprimentos/dashboard'
    | '/_authenticated/suprimentos/estoque'
    | '/api/public/atlas-exportar-baixas'
    | '/api/public/import-consumo-cmd'
    | '/api/public/import-consumo-op'
    | '/api/public/import-estoque-sistemico'
    | '/api/public/import-ficha-tecnica-bom'
    | '/_authenticated/baixas/'
    | '/_authenticated/config/'
    | '/_authenticated/missoes/'
    | '/_authenticated/producao/material/$material'
    | '/_authenticated/suprimentos/requisicoes/$id'
    | '/api/public/hooks/resumo-tarefas'
    | '/_authenticated/suprimentos/requisicoes/'
    | '/_authenticated/suprimentos/requisicoes/$id/ficha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicAtlasExportarBaixasRoute: typeof ApiPublicAtlasExportarBaixasRoute
  ApiPublicImportConsumoCmdRoute: typeof ApiPublicImportConsumoCmdRoute
  ApiPublicImportConsumoOpRoute: typeof ApiPublicImportConsumoOpRoute
  ApiPublicImportEstoqueSistemicoRoute: typeof ApiPublicImportEstoqueSistemicoRoute
  ApiPublicImportFichaTecnicaBomRoute: typeof ApiPublicImportFichaTecnicaBomRoute
  ApiPublicHooksResumoTarefasRoute: typeof ApiPublicHooksResumoTarefasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recontagem': {
      id: '/_authenticated/recontagem'
      path: '/recontagem'
      fullPath: '/recontagem'
      preLoaderRoute: typeof AuthenticatedRecontagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quebras-fefo': {
      id: '/_authenticated/quebras-fefo'
      path: '/quebras-fefo'
      fullPath: '/quebras-fefo'
      preLoaderRoute: typeof AuthenticatedQuebrasFefoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/origens': {
      id: '/_authenticated/origens'
      path: '/origens'
      fullPath: '/origens'
      preLoaderRoute: typeof AuthenticatedOrigensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motivos-baixa': {
      id: '/_authenticated/motivos-baixa'
      path: '/motivos-baixa'
      fullPath: '/motivos-baixa'
      preLoaderRoute: typeof AuthenticatedMotivosBaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar-familias': {
      id: '/_authenticated/importar-familias'
      path: '/importar-familias'
      fullPath: '/importar-familias'
      preLoaderRoute: typeof AuthenticatedImportarFamiliasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupos': {
      id: '/_authenticated/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AuthenticatedGruposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contar': {
      id: '/_authenticated/contar'
      path: '/contar'
      fullPath: '/contar'
      preLoaderRoute: typeof AuthenticatedContarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abc': {
      id: '/_authenticated/abc'
      path: '/abc'
      fullPath: '/abc'
      preLoaderRoute: typeof AuthenticatedAbcRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missoes/': {
      id: '/_authenticated/missoes/'
      path: '/missoes'
      fullPath: '/missoes/'
      preLoaderRoute: typeof AuthenticatedMissoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/': {
      id: '/_authenticated/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof AuthenticatedConfigIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/baixas/': {
      id: '/_authenticated/baixas/'
      path: '/baixas'
      fullPath: '/baixas/'
      preLoaderRoute: typeof AuthenticatedBaixasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/import-ficha-tecnica-bom': {
      id: '/api/public/import-ficha-tecnica-bom'
      path: '/api/public/import-ficha-tecnica-bom'
      fullPath: '/api/public/import-ficha-tecnica-bom'
      preLoaderRoute: typeof ApiPublicImportFichaTecnicaBomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/import-estoque-sistemico': {
      id: '/api/public/import-estoque-sistemico'
      path: '/api/public/import-estoque-sistemico'
      fullPath: '/api/public/import-estoque-sistemico'
      preLoaderRoute: typeof ApiPublicImportEstoqueSistemicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/import-consumo-op': {
      id: '/api/public/import-consumo-op'
      path: '/api/public/import-consumo-op'
      fullPath: '/api/public/import-consumo-op'
      preLoaderRoute: typeof ApiPublicImportConsumoOpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/import-consumo-cmd': {
      id: '/api/public/import-consumo-cmd'
      path: '/api/public/import-consumo-cmd'
      fullPath: '/api/public/import-consumo-cmd'
      preLoaderRoute: typeof ApiPublicImportConsumoCmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/atlas-exportar-baixas': {
      id: '/api/public/atlas-exportar-baixas'
      path: '/api/public/atlas-exportar-baixas'
      fullPath: '/api/public/atlas-exportar-baixas'
      preLoaderRoute: typeof ApiPublicAtlasExportarBaixasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suprimentos/estoque': {
      id: '/_authenticated/suprimentos/estoque'
      path: '/suprimentos/estoque'
      fullPath: '/suprimentos/estoque'
      preLoaderRoute: typeof AuthenticatedSuprimentosEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suprimentos/dashboard': {
      id: '/_authenticated/suprimentos/dashboard'
      path: '/suprimentos/dashboard'
      fullPath: '/suprimentos/dashboard'
      preLoaderRoute: typeof AuthenticatedSuprimentosDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shelf-life/risco': {
      id: '/_authenticated/shelf-life/risco'
      path: '/shelf-life/risco'
      fullPath: '/shelf-life/risco'
      preLoaderRoute: typeof AuthenticatedShelfLifeRiscoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shelf-life/precos': {
      id: '/_authenticated/shelf-life/precos'
      path: '/shelf-life/precos'
      fullPath: '/shelf-life/precos'
      preLoaderRoute: typeof AuthenticatedShelfLifePrecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shelf-life/farol': {
      id: '/_authenticated/shelf-life/farol'
      path: '/shelf-life/farol'
      fullPath: '/shelf-life/farol'
      preLoaderRoute: typeof AuthenticatedShelfLifeFarolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shelf-life/dashboard': {
      id: '/_authenticated/shelf-life/dashboard'
      path: '/shelf-life/dashboard'
      fullPath: '/shelf-life/dashboard'
      preLoaderRoute: typeof AuthenticatedShelfLifeDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shelf-life/acoes': {
      id: '/_authenticated/shelf-life/acoes'
      path: '/shelf-life/acoes'
      fullPath: '/shelf-life/acoes'
      preLoaderRoute: typeof AuthenticatedShelfLifeAcoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/testes-industriais': {
      id: '/_authenticated/producao/testes-industriais'
      path: '/producao/testes-industriais'
      fullPath: '/producao/testes-industriais'
      preLoaderRoute: typeof AuthenticatedProducaoTestesIndustriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/solicitacao-materiais': {
      id: '/_authenticated/producao/solicitacao-materiais'
      path: '/producao/solicitacao-materiais'
      fullPath: '/producao/solicitacao-materiais'
      preLoaderRoute: typeof AuthenticatedProducaoSolicitacaoMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/pcp': {
      id: '/_authenticated/producao/pcp'
      path: '/producao/pcp'
      fullPath: '/producao/pcp'
      preLoaderRoute: typeof AuthenticatedProducaoPcpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/dispersao': {
      id: '/_authenticated/producao/dispersao'
      path: '/producao/dispersao'
      fullPath: '/producao/dispersao'
      preLoaderRoute: typeof AuthenticatedProducaoDispersaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/auditoria-ft': {
      id: '/_authenticated/producao/auditoria-ft'
      path: '/producao/auditoria-ft'
      fullPath: '/producao/auditoria-ft'
      preLoaderRoute: typeof AuthenticatedProducaoAuditoriaFtRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missoes/$id': {
      id: '/_authenticated/missoes/$id'
      path: '/missoes/$id'
      fullPath: '/missoes/$id'
      preLoaderRoute: typeof AuthenticatedMissoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao/planejamento': {
      id: '/_authenticated/gestao/planejamento'
      path: '/gestao/planejamento'
      fullPath: '/gestao/planejamento'
      preLoaderRoute: typeof AuthenticatedGestaoPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao/modelos-checklist': {
      id: '/_authenticated/gestao/modelos-checklist'
      path: '/gestao/modelos-checklist'
      fullPath: '/gestao/modelos-checklist'
      preLoaderRoute: typeof AuthenticatedGestaoModelosChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao/minhas-tarefas': {
      id: '/_authenticated/gestao/minhas-tarefas'
      path: '/gestao/minhas-tarefas'
      fullPath: '/gestao/minhas-tarefas'
      preLoaderRoute: typeof AuthenticatedGestaoMinhasTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/sazonalidade': {
      id: '/_authenticated/config/sazonalidade'
      path: '/config/sazonalidade'
      fullPath: '/config/sazonalidade'
      preLoaderRoute: typeof AuthenticatedConfigSazonalidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/resend': {
      id: '/_authenticated/config/resend'
      path: '/config/resend'
      fullPath: '/config/resend'
      preLoaderRoute: typeof AuthenticatedConfigResendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/perfis': {
      id: '/_authenticated/config/perfis'
      path: '/config/perfis'
      fullPath: '/config/perfis'
      preLoaderRoute: typeof AuthenticatedConfigPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/inventario': {
      id: '/_authenticated/config/inventario'
      path: '/config/inventario'
      fullPath: '/config/inventario'
      preLoaderRoute: typeof AuthenticatedConfigInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/dispersao': {
      id: '/_authenticated/config/dispersao'
      path: '/config/dispersao'
      fullPath: '/config/dispersao'
      preLoaderRoute: typeof AuthenticatedConfigDispersaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/aparencia': {
      id: '/_authenticated/config/aparencia'
      path: '/config/aparencia'
      fullPath: '/config/aparencia'
      preLoaderRoute: typeof AuthenticatedConfigAparenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/baixas/dashboard': {
      id: '/_authenticated/baixas/dashboard'
      path: '/baixas/dashboard'
      fullPath: '/baixas/dashboard'
      preLoaderRoute: typeof AuthenticatedBaixasDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abastecimento/planejamento': {
      id: '/_authenticated/abastecimento/planejamento'
      path: '/abastecimento/planejamento'
      fullPath: '/abastecimento/planejamento'
      preLoaderRoute: typeof AuthenticatedAbastecimentoPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abastecimento/parametros': {
      id: '/_authenticated/abastecimento/parametros'
      path: '/abastecimento/parametros'
      fullPath: '/abastecimento/parametros'
      preLoaderRoute: typeof AuthenticatedAbastecimentoParametrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abastecimento/demandas': {
      id: '/_authenticated/abastecimento/demandas'
      path: '/abastecimento/demandas'
      fullPath: '/abastecimento/demandas'
      preLoaderRoute: typeof AuthenticatedAbastecimentoDemandasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abastecimento/consumo': {
      id: '/_authenticated/abastecimento/consumo'
      path: '/abastecimento/consumo'
      fullPath: '/abastecimento/consumo'
      preLoaderRoute: typeof AuthenticatedAbastecimentoConsumoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suprimentos/requisicoes/': {
      id: '/_authenticated/suprimentos/requisicoes/'
      path: '/suprimentos/requisicoes'
      fullPath: '/suprimentos/requisicoes/'
      preLoaderRoute: typeof AuthenticatedSuprimentosRequisicoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/resumo-tarefas': {
      id: '/api/public/hooks/resumo-tarefas'
      path: '/api/public/hooks/resumo-tarefas'
      fullPath: '/api/public/hooks/resumo-tarefas'
      preLoaderRoute: typeof ApiPublicHooksResumoTarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suprimentos/requisicoes/$id': {
      id: '/_authenticated/suprimentos/requisicoes/$id'
      path: '/suprimentos/requisicoes/$id'
      fullPath: '/suprimentos/requisicoes/$id'
      preLoaderRoute: typeof AuthenticatedSuprimentosRequisicoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/material/$material': {
      id: '/_authenticated/producao/material/$material'
      path: '/producao/material/$material'
      fullPath: '/producao/material/$material'
      preLoaderRoute: typeof AuthenticatedProducaoMaterialMaterialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suprimentos/requisicoes/$id/ficha': {
      id: '/_authenticated/suprimentos/requisicoes/$id/ficha'
      path: '/ficha'
      fullPath: '/suprimentos/requisicoes/$id/ficha'
      preLoaderRoute: typeof AuthenticatedSuprimentosRequisicoesIdFichaRouteImport
      parentRoute: typeof AuthenticatedSuprimentosRequisicoesIdRoute
    }
  }
}

interface AuthenticatedSuprimentosRequisicoesIdRouteChildren {
  AuthenticatedSuprimentosRequisicoesIdFichaRoute: typeof AuthenticatedSuprimentosRequisicoesIdFichaRoute
}

const AuthenticatedSuprimentosRequisicoesIdRouteChildren: AuthenticatedSuprimentosRequisicoesIdRouteChildren =
  {
    AuthenticatedSuprimentosRequisicoesIdFichaRoute:
      AuthenticatedSuprimentosRequisicoesIdFichaRoute,
  }

const AuthenticatedSuprimentosRequisicoesIdRouteWithChildren =
  AuthenticatedSuprimentosRequisicoesIdRoute._addFileChildren(
    AuthenticatedSuprimentosRequisicoesIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbcRoute: typeof AuthenticatedAbcRoute
  AuthenticatedContarRoute: typeof AuthenticatedContarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedGruposRoute: typeof AuthenticatedGruposRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedImportarFamiliasRoute: typeof AuthenticatedImportarFamiliasRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMotivosBaixaRoute: typeof AuthenticatedMotivosBaixaRoute
  AuthenticatedOrigensRoute: typeof AuthenticatedOrigensRoute
  AuthenticatedQuebrasFefoRoute: typeof AuthenticatedQuebrasFefoRoute
  AuthenticatedRecontagemRoute: typeof AuthenticatedRecontagemRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedAbastecimentoConsumoRoute: typeof AuthenticatedAbastecimentoConsumoRoute
  AuthenticatedAbastecimentoDemandasRoute: typeof AuthenticatedAbastecimentoDemandasRoute
  AuthenticatedAbastecimentoParametrosRoute: typeof AuthenticatedAbastecimentoParametrosRoute
  AuthenticatedAbastecimentoPlanejamentoRoute: typeof AuthenticatedAbastecimentoPlanejamentoRoute
  AuthenticatedBaixasDashboardRoute: typeof AuthenticatedBaixasDashboardRoute
  AuthenticatedConfigAparenciaRoute: typeof AuthenticatedConfigAparenciaRoute
  AuthenticatedConfigDispersaoRoute: typeof AuthenticatedConfigDispersaoRoute
  AuthenticatedConfigInventarioRoute: typeof AuthenticatedConfigInventarioRoute
  AuthenticatedConfigPerfisRoute: typeof AuthenticatedConfigPerfisRoute
  AuthenticatedConfigResendRoute: typeof AuthenticatedConfigResendRoute
  AuthenticatedConfigSazonalidadeRoute: typeof AuthenticatedConfigSazonalidadeRoute
  AuthenticatedGestaoMinhasTarefasRoute: typeof AuthenticatedGestaoMinhasTarefasRoute
  AuthenticatedGestaoModelosChecklistRoute: typeof AuthenticatedGestaoModelosChecklistRoute
  AuthenticatedGestaoPlanejamentoRoute: typeof AuthenticatedGestaoPlanejamentoRoute
  AuthenticatedMissoesIdRoute: typeof AuthenticatedMissoesIdRoute
  AuthenticatedProducaoAuditoriaFtRoute: typeof AuthenticatedProducaoAuditoriaFtRoute
  AuthenticatedProducaoDispersaoRoute: typeof AuthenticatedProducaoDispersaoRoute
  AuthenticatedProducaoPcpRoute: typeof AuthenticatedProducaoPcpRoute
  AuthenticatedProducaoSolicitacaoMateriaisRoute: typeof AuthenticatedProducaoSolicitacaoMateriaisRoute
  AuthenticatedProducaoTestesIndustriaisRoute: typeof AuthenticatedProducaoTestesIndustriaisRoute
  AuthenticatedShelfLifeAcoesRoute: typeof AuthenticatedShelfLifeAcoesRoute
  AuthenticatedShelfLifeDashboardRoute: typeof AuthenticatedShelfLifeDashboardRoute
  AuthenticatedShelfLifeFarolRoute: typeof AuthenticatedShelfLifeFarolRoute
  AuthenticatedShelfLifePrecosRoute: typeof AuthenticatedShelfLifePrecosRoute
  AuthenticatedShelfLifeRiscoRoute: typeof AuthenticatedShelfLifeRiscoRoute
  AuthenticatedSuprimentosDashboardRoute: typeof AuthenticatedSuprimentosDashboardRoute
  AuthenticatedSuprimentosEstoqueRoute: typeof AuthenticatedSuprimentosEstoqueRoute
  AuthenticatedBaixasIndexRoute: typeof AuthenticatedBaixasIndexRoute
  AuthenticatedConfigIndexRoute: typeof AuthenticatedConfigIndexRoute
  AuthenticatedMissoesIndexRoute: typeof AuthenticatedMissoesIndexRoute
  AuthenticatedProducaoMaterialMaterialRoute: typeof AuthenticatedProducaoMaterialMaterialRoute
  AuthenticatedSuprimentosRequisicoesIdRoute: typeof AuthenticatedSuprimentosRequisicoesIdRouteWithChildren
  AuthenticatedSuprimentosRequisicoesIndexRoute: typeof AuthenticatedSuprimentosRequisicoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbcRoute: AuthenticatedAbcRoute,
  AuthenticatedContarRoute: AuthenticatedContarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedGruposRoute: AuthenticatedGruposRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedImportarFamiliasRoute: AuthenticatedImportarFamiliasRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMotivosBaixaRoute: AuthenticatedMotivosBaixaRoute,
  AuthenticatedOrigensRoute: AuthenticatedOrigensRoute,
  AuthenticatedQuebrasFefoRoute: AuthenticatedQuebrasFefoRoute,
  AuthenticatedRecontagemRoute: AuthenticatedRecontagemRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedAbastecimentoConsumoRoute:
    AuthenticatedAbastecimentoConsumoRoute,
  AuthenticatedAbastecimentoDemandasRoute:
    AuthenticatedAbastecimentoDemandasRoute,
  AuthenticatedAbastecimentoParametrosRoute:
    AuthenticatedAbastecimentoParametrosRoute,
  AuthenticatedAbastecimentoPlanejamentoRoute:
    AuthenticatedAbastecimentoPlanejamentoRoute,
  AuthenticatedBaixasDashboardRoute: AuthenticatedBaixasDashboardRoute,
  AuthenticatedConfigAparenciaRoute: AuthenticatedConfigAparenciaRoute,
  AuthenticatedConfigDispersaoRoute: AuthenticatedConfigDispersaoRoute,
  AuthenticatedConfigInventarioRoute: AuthenticatedConfigInventarioRoute,
  AuthenticatedConfigPerfisRoute: AuthenticatedConfigPerfisRoute,
  AuthenticatedConfigResendRoute: AuthenticatedConfigResendRoute,
  AuthenticatedConfigSazonalidadeRoute: AuthenticatedConfigSazonalidadeRoute,
  AuthenticatedGestaoMinhasTarefasRoute: AuthenticatedGestaoMinhasTarefasRoute,
  AuthenticatedGestaoModelosChecklistRoute:
    AuthenticatedGestaoModelosChecklistRoute,
  AuthenticatedGestaoPlanejamentoRoute: AuthenticatedGestaoPlanejamentoRoute,
  AuthenticatedMissoesIdRoute: AuthenticatedMissoesIdRoute,
  AuthenticatedProducaoAuditoriaFtRoute: AuthenticatedProducaoAuditoriaFtRoute,
  AuthenticatedProducaoDispersaoRoute: AuthenticatedProducaoDispersaoRoute,
  AuthenticatedProducaoPcpRoute: AuthenticatedProducaoPcpRoute,
  AuthenticatedProducaoSolicitacaoMateriaisRoute:
    AuthenticatedProducaoSolicitacaoMateriaisRoute,
  AuthenticatedProducaoTestesIndustriaisRoute:
    AuthenticatedProducaoTestesIndustriaisRoute,
  AuthenticatedShelfLifeAcoesRoute: AuthenticatedShelfLifeAcoesRoute,
  AuthenticatedShelfLifeDashboardRoute: AuthenticatedShelfLifeDashboardRoute,
  AuthenticatedShelfLifeFarolRoute: AuthenticatedShelfLifeFarolRoute,
  AuthenticatedShelfLifePrecosRoute: AuthenticatedShelfLifePrecosRoute,
  AuthenticatedShelfLifeRiscoRoute: AuthenticatedShelfLifeRiscoRoute,
  AuthenticatedSuprimentosDashboardRoute:
    AuthenticatedSuprimentosDashboardRoute,
  AuthenticatedSuprimentosEstoqueRoute: AuthenticatedSuprimentosEstoqueRoute,
  AuthenticatedBaixasIndexRoute: AuthenticatedBaixasIndexRoute,
  AuthenticatedConfigIndexRoute: AuthenticatedConfigIndexRoute,
  AuthenticatedMissoesIndexRoute: AuthenticatedMissoesIndexRoute,
  AuthenticatedProducaoMaterialMaterialRoute:
    AuthenticatedProducaoMaterialMaterialRoute,
  AuthenticatedSuprimentosRequisicoesIdRoute:
    AuthenticatedSuprimentosRequisicoesIdRouteWithChildren,
  AuthenticatedSuprimentosRequisicoesIndexRoute:
    AuthenticatedSuprimentosRequisicoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicAtlasExportarBaixasRoute: ApiPublicAtlasExportarBaixasRoute,
  ApiPublicImportConsumoCmdRoute: ApiPublicImportConsumoCmdRoute,
  ApiPublicImportConsumoOpRoute: ApiPublicImportConsumoOpRoute,
  ApiPublicImportEstoqueSistemicoRoute: ApiPublicImportEstoqueSistemicoRoute,
  ApiPublicImportFichaTecnicaBomRoute: ApiPublicImportFichaTecnicaBomRoute,
  ApiPublicHooksResumoTarefasRoute: ApiPublicHooksResumoTarefasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
