/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRecontagemRouteImport } from './routes/_authenticated/recontagem'
import { Route as AuthenticatedMissoesRouteImport } from './routes/_authenticated/missoes'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedImportarFamiliasRouteImport } from './routes/_authenticated/importar-familias'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedGruposRouteImport } from './routes/_authenticated/grupos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContarRouteImport } from './routes/_authenticated/contar'
import { Route as AuthenticatedConfigRouteImport } from './routes/_authenticated/config'
import { Route as AuthenticatedBaixasRouteImport } from './routes/_authenticated/baixas'
import { Route as AuthenticatedAbcRouteImport } from './routes/_authenticated/abc'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecontagemRoute = AuthenticatedRecontagemRouteImport.update({
  id: '/recontagem',
  path: '/recontagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissoesRoute = AuthenticatedMissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarFamiliasRoute =
  AuthenticatedImportarFamiliasRouteImport.update({
    id: '/importar-familias',
    path: '/importar-familias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGruposRoute = AuthenticatedGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContarRoute = AuthenticatedContarRouteImport.update({
  id: '/contar',
  path: '/contar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaixasRoute = AuthenticatedBaixasRouteImport.update({
  id: '/baixas',
  path: '/baixas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAbcRoute = AuthenticatedAbcRouteImport.update({
  id: '/abc',
  path: '/abc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/abc': typeof AuthenticatedAbcRoute
  '/baixas': typeof AuthenticatedBaixasRoute
  '/config': typeof AuthenticatedConfigRoute
  '/contar': typeof AuthenticatedContarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/importar-familias': typeof AuthenticatedImportarFamiliasRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/missoes': typeof AuthenticatedMissoesRoute
  '/recontagem': typeof AuthenticatedRecontagemRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/abc': typeof AuthenticatedAbcRoute
  '/baixas': typeof AuthenticatedBaixasRoute
  '/config': typeof AuthenticatedConfigRoute
  '/contar': typeof AuthenticatedContarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/importar-familias': typeof AuthenticatedImportarFamiliasRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/missoes': typeof AuthenticatedMissoesRoute
  '/recontagem': typeof AuthenticatedRecontagemRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/abc': typeof AuthenticatedAbcRoute
  '/_authenticated/baixas': typeof AuthenticatedBaixasRoute
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/contar': typeof AuthenticatedContarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/grupos': typeof AuthenticatedGruposRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/importar-familias': typeof AuthenticatedImportarFamiliasRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/missoes': typeof AuthenticatedMissoesRoute
  '/_authenticated/recontagem': typeof AuthenticatedRecontagemRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/abc'
    | '/baixas'
    | '/config'
    | '/contar'
    | '/dashboard'
    | '/grupos'
    | '/importar'
    | '/importar-familias'
    | '/inventario'
    | '/logs'
    | '/missoes'
    | '/recontagem'
    | '/relatorios'
    | '/scanner'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/abc'
    | '/baixas'
    | '/config'
    | '/contar'
    | '/dashboard'
    | '/grupos'
    | '/importar'
    | '/importar-familias'
    | '/inventario'
    | '/logs'
    | '/missoes'
    | '/recontagem'
    | '/relatorios'
    | '/scanner'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/abc'
    | '/_authenticated/baixas'
    | '/_authenticated/config'
    | '/_authenticated/contar'
    | '/_authenticated/dashboard'
    | '/_authenticated/grupos'
    | '/_authenticated/importar'
    | '/_authenticated/importar-familias'
    | '/_authenticated/inventario'
    | '/_authenticated/logs'
    | '/_authenticated/missoes'
    | '/_authenticated/recontagem'
    | '/_authenticated/relatorios'
    | '/_authenticated/scanner'
    | '/_authenticated/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recontagem': {
      id: '/_authenticated/recontagem'
      path: '/recontagem'
      fullPath: '/recontagem'
      preLoaderRoute: typeof AuthenticatedRecontagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missoes': {
      id: '/_authenticated/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof AuthenticatedMissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar-familias': {
      id: '/_authenticated/importar-familias'
      path: '/importar-familias'
      fullPath: '/importar-familias'
      preLoaderRoute: typeof AuthenticatedImportarFamiliasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupos': {
      id: '/_authenticated/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AuthenticatedGruposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contar': {
      id: '/_authenticated/contar'
      path: '/contar'
      fullPath: '/contar'
      preLoaderRoute: typeof AuthenticatedContarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/baixas': {
      id: '/_authenticated/baixas'
      path: '/baixas'
      fullPath: '/baixas'
      preLoaderRoute: typeof AuthenticatedBaixasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abc': {
      id: '/_authenticated/abc'
      path: '/abc'
      fullPath: '/abc'
      preLoaderRoute: typeof AuthenticatedAbcRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbcRoute: typeof AuthenticatedAbcRoute
  AuthenticatedBaixasRoute: typeof AuthenticatedBaixasRoute
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedContarRoute: typeof AuthenticatedContarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGruposRoute: typeof AuthenticatedGruposRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedImportarFamiliasRoute: typeof AuthenticatedImportarFamiliasRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMissoesRoute: typeof AuthenticatedMissoesRoute
  AuthenticatedRecontagemRoute: typeof AuthenticatedRecontagemRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbcRoute: AuthenticatedAbcRoute,
  AuthenticatedBaixasRoute: AuthenticatedBaixasRoute,
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedContarRoute: AuthenticatedContarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGruposRoute: AuthenticatedGruposRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedImportarFamiliasRoute: AuthenticatedImportarFamiliasRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMissoesRoute: AuthenticatedMissoesRoute,
  AuthenticatedRecontagemRoute: AuthenticatedRecontagemRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
