
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'COORDENADOR_CONTROLE';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'VENDEDOR';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'OPERADOR_ESTOQUE';
